Created shopping lists preview component.
magmat88/shopping-notes pull request #6
Opened 2022-01-11 14:09 UTC by magmat88

Created shopping list tile component  with icon and
title of shopping list.

2022-01-11 21:15 UTC, earendillo requested changes

2022-01-11 21:15 UTC, earendillo commented on src/app/components/shoppingListsPreview/shoppingListsPreview.component.tsx
> +                <ShoppingListTile shoppingList={shoppingLists[0]} />
use map instead of using indexes, e.g.: `{shoppingLists.map((shoppingList: ShoppingList) => <ShoppingListTile shoppingList={shoppingList]} />)}`

2022-01-11 21:15 UTC, earendillo commented on src/app/components/shoppingListsPreview/shoppingListsPreview.component.scss
> +    width: 90vh;
why do you use vh for declaring `width`? please change to certain `vw` value

2022-01-11 21:15 UTC, earendillo commented on src/app/components/shoppingListsPreview/shoppingListsPreview.component.scss
> +    width: 90vh;
why do you use vh for declaring width? please change to certain vw value

2022-01-11 21:15 UTC, earendillo commented on src/app/styles/variables/colors.scss
>  $color_medium: #8E8E93;
I know this line was not change during work on this issue but please rename it - color_medium means nothing - be more descriptive

2022-01-11 21:15 UTC, earendillo commented on src/app/components/shoppingListTile/shoppingListTile.component.tsx
> +export function ShoppingListTile({ shoppingList }: ShoppingListTileProps) {
function is missing return type

2022-01-11 21:15 UTC, earendillo commented on src/app/components/shoppingListTile/shoppingListTile.component.tsx
> +    const [iconColor, setIconColor] = useState(shoppingList.listIcon.color);
use generic types for useState() declarations, e.g. useState<string>(someValue)

2022-01-11 21:15 UTC, earendillo commented on src/app/app.tsx
>  export function App() {
I know it's old code but please add return type

2022-01-11 21:15 UTC, earendillo commented on src/app/app.tsx
> +                    numberOfItems: 4
`count` means exactly the same what `numberOfItems` but is much more shorter :)

2022-01-11 21:15 UTC, earendillo commented on src/app/app.tsx
> +            <ShoppingListsPreview
So this is note strict issue with the code as it will be change later when the app grows but please consider such excercise to extract certain components to render functions to avoid so extensive return statement for app component, e.g.:
`function renderShoppingListsPreview() { // put code which renders ShoppingListsPreview component here }

2022-01-11 21:15 UTC, earendillo commented on src/app/app.tsx
> +                shoppingLists={[
also these mocked shoppingLists could be extracted to const shoppingLists = [// put these mocked values here]. this declarations could be moved outside this file to some config file

2022-01-11 21:15 UTC, earendillo commented on src/app/app.tsx
> +                product={{
extract this plain object to some const

2022-01-11 21:54 UTC, magmat88 commented on src/app/app.scss
> +    font-family:$font-main, $font-alternative;
this change has been reverted

2022-01-11 22:18 UTC, magmat88 commented on src/app/components/navigationBar/navigationBar.component.scss
> +            width: 82.5vw;
corrected to integer value

2022-01-11 22:20 UTC, magmat88 commented on src/app/components/navigationBar/navigationBar.component.scss
> +            width: 7.5vw;
corrected to an integer value

2022-01-11 22:27 UTC, magmat88 commented on src/app/components/shoppingListsPreview/shoppingListsPreview.component.scss
> +.shopping-lists-preview-items {
changed name of the main class and nested other classed inside this class

2022-01-11 22:29 UTC, magmat88 commented on src/app/components/shoppingListTile/shoppingListTile.component.scss
> +.shopping-list-tile {
nested all other classes inside main class

2022-01-11 22:40 UTC, magmat88 commented on src/app/app.tsx
>  export function App() {
added return type of function component

2022-01-11 22:43 UTC, magmat88 commented on src/app/app.tsx
> +                    numberOfItems: 4
numberOfItems name changed to quantity

2022-01-11 22:54 UTC, magmat88 commented on src/app/app.tsx
> +            <ShoppingListsPreview
extracted every nested component to the separate render function

2022-01-12 22:38 UTC, magmat88 commented on src/app/app.tsx
> +                shoppingLists={[
created staticContent file with shoppingLists containing mocked values

2022-01-12 22:44 UTC, magmat88 commented on src/app/app.tsx
> +                product={{
created products contstant with mocked content and placed in staticContent file

2022-01-13 21:35 UTC, merged